layout_spectrum: 0
color:
  saturation: 0.1917563
  brandStrength: 0.4910394
  lightness: 0.1469534
  brandColors:
    - '#FFFFFF'
    - '#4B4A43'
    - '#030202'
    - '#BFBFBF'
  rhythmicContrast: 0.553839
typography_spectrum: 0.5394265
name: Brave
